image: $CI_REGISTRY/r3/docker/julia-custom

stages:
  - test
  - deploy-doc

test:
  stage: test

  script:
    - julia --project=@. -e "import Pkg; Pkg.test(; coverage = true)"

  after_script:
    - julia -e 'using Pkg; using Coverage; Codecov.submit_local(process_folder())'