language: julia

branches:
  only:
    - develop
    - master

os:
    - linux

julia:
    - 1.0
    - 1.5
    - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
    email: false
